# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin

class musicLink(BasePlugin):

    async def initialize(self) -> None:
        # Will be called when plugin is launching
        pass

    def __del__(self) -> None:
        # Will be called when plugin is terminating
        pass